### PR TITLE
Added two extra functionalities.

### PR DESCRIPTION
**Pull request by mhdbny**
1. Enable users to pick slices from the time slice model.
2. Add an easy way to save the one-to-one surveillance plots.

### CODE REVIEW

**Comment by mhdbny** [comment]
Prof. Gerber -
Could you please merge these changes?

Thanks,
Mohammad

**Comment by MatthewGerber** [comment]
Mohammad -

It's on my list but I probably won't get to it for a while unless you need
it for your work for some reason.

Matt

**Comment by mhdbny** [comment]
Prof. Gerber -
Not really. I just fixed the surveillance plots and wanted to include the fix in the current pull. 

Mohammad

**Comment by MatthewGerber** [comment]
Mohammad - Do you still need this PR or should I delete it?

**Comment by mhdbny** [comment]
Prof. Gerber - You can delete it. I already added the two functions to the last build.  Also, I am running some tests, and will push a newer version today. Could you please merge it as well? Thank you!

**Pull request closed without merging**
